name: ".travis.yml"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        env: 
            TOXENV: ${{ matrix.test }}
            RUN_INTEGRATION_TESTS: ${{ matrix.test_number}}
        steps:
            - uses: actions/checkout@v3
            - run: pip install "tox"
            - run: pip install bandit
            - run: pip install codecov
            - run: pip install slugs
            - run: sudo chmod -R 777 /usr/local/lib/
            - run: python3 setup.py install
            - run: RUN_INTEGRATION_TESTS=${{ matrix.test_number }} ./.travis/run.sh
            - run: codecov
        strategy:
            matrix:
                test: ["pep8", "bandit", "docs"]
                test_number: ["0","1"]
                os: [ubuntu-22.04,ubuntu-20.04]
                include:
                    - test: "py38"
                      os: ubuntu-20.04
                    - test: "py310"
                      os: ubuntu-22.04