name: ".travis.yml"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        env: 
            TOXENV: ${{ matrix.test }}
            RUN_INTEGRATION_TESTS: ${{ (matrix.test == 'bandit' || matrix.test == 'pep8' || matrix.test == 'docs') && '0' || matrix.test_number}}
        steps:
            - uses: actions/checkout@v2
            - run: pip uninstall -y six
            - run: pip install six>=1.11.0
            - run: pip install "more_itertools<=7.2.0"
            - run: pip install "tox<=3.14.1"
            - run: pip install "PyYAML<=5.2"
            - run: pip install bandit
            - run: pip install codecov
            - run: pip install slugs
            
            - run: ./.travis/run.sh
            - run: codecov
        strategy:
            matrix:
                test: ['py27', 'py34', 'py35', 'py36', 'py37', 'pep8', 'bandit', 'docs']
                test_number: ['0', '1' , '2']
                os: [ubuntu-20.04, ubuntu-22.04]
                
  