name: "Run Travis.yml"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
        -   name: Run .travis.yml build script
            uses: ktomk/run-travis-yml@v1.8.1
            with:
                file: .travis.yml
                steps: |
                    install
                    script
                allow-failure: false